dbeef/spelunky-psp

- cmake/CurrentPlatform.cmake
Before:
```shell
dbeef@dbeefstation:~/spelunky-psp$ ls -sh ./tmp/build-psp/EBOOT.PBP
11M ./tmp/build-psp/EBOOT.PBP
```
After:
```shell
dbeef@dbeefstation:~/spelunky-psp$  ls -sh ./tmp/build-psp/EBOOT.PBP
1.6M ./tmp/build-psp/EBOOT.PBP
```
> Stripping binary post-build

- .travis.yml
- cmake/CurrentPlatform.cmake
- vendor/cjson/CMakeLists.txt
Hi!
Apart from fixing install paths (tsk, tsk) and running the PSP artifact through `psp-strip` only, additionally `cJSON` is no longer installed by `CMake`.
Best
Rafal
> Fixed binaries' install path, cleanup

- src/camera/interface/Camera.hpp
- src/camera/src/Camera.cpp
- src/game-loop/CMakeLists.txt
- src/game-loop/include/components/CameraComponent.hpp
- src/game-loop/include/main-dude/MainDude.hpp
- src/game-loop/src/GameLoop.cpp
- src/game-loop/src/components/CameraComponent.cpp
- src/game-loop/src/main-dude/states/MainDudeCrawlingState.cpp
- src/game-loop/src/main-dude/states/MainDudeDuckingState.cpp
- src/game-loop/src/main-dude/states/MainDudeExitingState.cpp
- src/game-loop/src/main-dude/states/MainDudeFallingState.cpp
- src/game-loop/src/main-dude/states/MainDudeJumpingState.cpp
- src/game-loop/src/main-dude/states/MainDudePushingState.cpp
- src/game-loop/src/main-dude/states/MainDudeRunningState.cpp
- src/game-loop/src/main-dude/states/MainDudeStandingState.cpp
- src/game-loop/src/main-dude/states/MainDudeThrowingState.cpp
What I'd like to see in this PR:
Stopping the camera at level's border might require small refactoring.
EDIT: I'll drop the topics for now, let's not do too much.
> Camera following MainDude when out of a bounding box

- CMakeLists.txt
- tools/resource_compiler/src/Main.cpp
- tools/texture_packer/3rdparty/sx/CMakeLists.txt
Howdy! During my -- albeit failed -- attempt to bring the resource compiler closer to CMake, I found the following issues building the third-party tools on Windows.
I am temporarily dropping the topic of a resource compiler callable from CMake, as this would require a broader discussion around cross-compilation.
> Fixing 3rdparty tools issues on Windows

- src/game-loop/src/game-loop/GameLoopLevelSummaryState.cpp
- src/game-loop/src/game-loop/GameLoopMainMenuState.cpp
- src/game-loop/src/game-loop/GameLoopPlayingState.cpp
- src/game-loop/src/game-loop/GameLoopStartedState.cpp
Level render entities were added every time when level was re-generated, but not disposed, resulting
on levels being rendered on top of each other.
Manifested as FPS drastically dropping on hardware-constrained platforms like PSP.
> Bugfix for duplicating level render entities.

- CMakeLists.txt
- src/Main.cpp
- src/camera/CMakeLists.txt
- src/camera/interface/ModelViewCamera.hpp
- src/camera/interface/ScreenSpaceCamera.hpp
- src/camera/src/ModelViewCamera.cpp
- src/camera/src/ScreenSpaceCamera.cpp
- src/game-loop/CMakeLists.txt
- src/game-loop/include/game-objects/HUD.hpp
- src/game-loop/interface/GameLoop.hpp
- src/game-loop/src/game-loop/GameLoop.cpp
- src/game-loop/src/game-loop/GameLoopPlayingState.cpp
- src/game-loop/src/game-objects/HUD.cpp
- src/graphics-utils/src/CreateTexture.cpp
- src/renderer/CMakeLists.txt
- src/renderer/src/Renderer.cpp
- src/time/interface/time/Timestep.hpp
- src/time/src/Timestep.cpp
- src/video/CMakeLists.txt
- src/video/interface/video/Context.hpp
- src/video/src/Context.cpp
- src/video/src/Context_Desktop.cpp
- src/video/src/Context_PSP.cpp
- src/viewport/CMakeLists.txt
- src/viewport/interface/viewport/Viewport.hpp
I'd like to introduce this decoupling in order to remove Video's two-face behaviour - no code other than `Main.cpp` should have access to display functions. Most of what's inside the game actually only needs viewport hints.
Also, I removed another singleton!
Rafal
> Decoupling Viewport from Video Context

- cmake/DependenciesLinux.cmake
- cmake/DependenciesPSP.cmake
- cmake/DependenciesWindows.cmake
For Windows, the `Dependencies` target is empty, but I've decoupled it from SDL now
> Remove SDL_1_XX from Dependencies target

- CMakeLists.txt
- src/camera/CMakeLists.txt
- src/texture-bank/CMakeLists.txt
- src/texture-bank/interface/TextureBank.hpp
- src/texture-bank/interface/TextureRegion.hpp
Removes glad where it's obsolete or easy to hide from the interface
> Proposal for simple glad removal in CMake dependencies tree

- src/game-loop/CMakeLists.txt
- src/game-loop/src/game-loop/GameLoop.cpp
(this is after rebasing on previous PRs)
One thing that made me worried is graphviz not visualising the fact that `Input` depends on `SDL`. This could be a limitation of the tool.
> Decoupled GameLoop from glad & GraphicsUtils

- src/time/interface/time/Timestep.hpp
- src/time/src/Timestep.cpp
- src/video/interface/video/Context.hpp
- src/video/src/Context.cpp
`Timestep::delay()` wasn't doing what it was supposed to. 
I would suggest a different approach whatsoever, for the physics engine to work better: either cumulating time differences to apply when they pass minimum timing thresholds, or uncapping the framerate and using non-floating point variables to track time, velocity and position changes
I would appreciate testing on Linux.
Waiting for #33 to be merged first
> Proposal for Windows timing fix

- src/game-loop/src/components/PhysicsComponent.cpp
Reproduction steps:
1. Start the game
2. Keep pressing left/right and then add pressing right/left
This fix addresses this minor bug, as well as a potential similar issue within the `y` dimension check.
> Fixing wall pushing state on simultaneous LR movement

- src/game-loop/src/main-dude/states/MainDudeCliffHangingState.cpp
- src/game-loop/src/main-dude/states/MainDudeClimbingLadderState.cpp
- src/game-loop/src/main-dude/states/MainDudeCrawlingState.cpp
- src/game-loop/src/main-dude/states/MainDudeDuckingState.cpp
- src/game-loop/src/main-dude/states/MainDudeFallingState.cpp
- src/game-loop/src/main-dude/states/MainDudeJumpingState.cpp
- src/game-loop/src/main-dude/states/MainDudeLookingUpState.cpp
- src/game-loop/src/main-dude/states/MainDudePushingState.cpp
- src/game-loop/src/main-dude/states/MainDudeRunningLookingUpState.cpp
- src/game-loop/src/main-dude/states/MainDudeRunningState.cpp
- src/game-loop/src/main-dude/states/MainDudeStandingState.cpp
- src/game-loop/src/main-dude/states/MainDudeThrowingState.cpp
- src/input/interface/Input.hpp
- src/input/src/Input_Desktop.cpp
- src/input/src/Input_PSP.cpp
- src/video/src/Context.cpp
Remembering key-action mapping is troubling, better to place it in the interface directly and resolve mapping in
the platform-specific implementation.
> Input interface refactor - mapping keys to specific actions

- src/camera/interface/ScreenSpaceCamera.hpp
- src/camera/src/ModelViewCamera.cpp
- src/camera/src/ScreenSpaceCamera.cpp
- src/game-loop/include/game-objects/HUD.hpp
- src/game-loop/include/game-objects/TextBuffer.hpp
- src/game-loop/src/game-loop/GameLoop.cpp
- src/game-loop/src/game-objects/HUD.cpp
- src/game-loop/src/game-objects/PausePlayingGame.cpp
- src/game-loop/src/game-objects/TextBuffer.cpp
- src/video/src/Context_PSP.cpp
- src/viewport/interface/viewport/Viewport.hpp
So far rendering HUD and pause screen was fine as long as the resolution was fixed to 480x272 (PSP's native).
However, when running fullscreen on desktop, screen-space quads become extremely small:
This PR re-defines screen-space quads' dimensions in terms of world units, rather than in pixels.
World units depend on the screen resolution (to keep the same number of tiles rendered on the screen on every device), meaning they are more portable way of defining size.
> Screen-space quads using world-units to adapt to non-fixed resolution

- src/game-loop/CMakeLists.txt
- src/game-loop/include/game-objects/CopyrightsSign.hpp
- src/game-loop/include/game-objects/DeathOverlay.hpp
- src/game-loop/include/game-objects/GameEntity.hpp
- src/game-loop/include/game-objects/HUD.hpp
- src/game-loop/include/game-objects/MainLogo.hpp
- src/game-loop/include/game-objects/PauseOverlay.hpp
- src/game-loop/include/game-objects/QuitSign.hpp
- src/game-loop/include/game-objects/ResetSign.hpp
- src/game-loop/include/game-objects/ScoresSign.hpp
- src/game-loop/include/game-objects/StartSign.hpp
- src/game-loop/include/game-objects/TextBuffer.hpp
- src/game-loop/include/game-objects/TutorialSign.hpp
- src/game-loop/include/main-dude/MainDude.hpp
- src/game-loop/interface/GameLoop.hpp
- src/game-loop/src/game-loop/GameLoopPlayingState.cpp
`GameEntity` fits more to the terminology used within the project, i.e there's already a `RenderEntity`, and as former `GameObject`-s are composed out of `Component`-s, it would fit more to the idea of the [entity-component-system](https://en.wikipedia.org/wiki/Entity_component_system).
> Renamed GameObject to GameEntity

- src/game-loop/include/game-entities/TextBuffer.hpp
- src/game-loop/src/game-entities/DeathOverlay.cpp
- src/game-loop/src/game-entities/PauseOverlay.cpp
- src/game-loop/src/game-entities/TextBuffer.cpp
As in the title.
Applied in the `PauseOverlay`:
While tinkering with the `TextBuffer` with this and other MR's (https://github.com/dbeef/spelunky-psp/pull/56, https://github.com/dbeef/spelunky-psp/pull/58) I came into conclusion that the text rendering API must be re-worked, as it is very much a C-style API, verbose with its syntax. Something more RAII-like would fit better as after all, this is a C++ 14 project.
> Added optional font scaling to the TextBuffer API.

- src/game-loop/CMakeLists.txt
- src/game-loop/include/game-entities/ScoresOverlay.hpp
- src/game-loop/interface/GameLoopScoresState.hpp
- src/game-loop/src/game-entities/ScoresOverlay.cpp
- src/game-loop/src/game-loop/GameLoopScoresState.cpp
Not functional in terms of reading any in-game statistics from persistent memory, displays dummy data.
> Scores screen overlay with statistics

- src/game-loop/CMakeLists.txt
- src/game-loop/include/game-entities/LevelSummaryOverlay.hpp
- src/game-loop/interface/GameLoopLevelSummaryState.hpp
- src/game-loop/src/game-entities/LevelSummaryOverlay.cpp
- src/game-loop/src/game-loop/GameLoopLevelSummaryState.cpp
Not functional in terms of keeping track of the last level. Displays dummy data.
> Added level summary overlay with statistics

- src/game-loop/CMakeLists.txt
- src/game-loop/include/game-entities/HUD.hpp
- src/game-loop/include/main-dude/MainDude.hpp
- src/game-loop/include/main-dude/MainDudeEvent.hpp
- src/game-loop/src/game-entities/HUD.cpp
- src/game-loop/src/game-loop/GameLoopPlayingState.cpp
- src/game-loop/src/main-dude/MainDude.cpp
- src/game-loop/src/main-dude/states/MainDudeStunnedState.cpp
- src/patterns/interface/patterns/Observer.hpp
- src/patterns/interface/patterns/Subject.hpp
The observer pattern, as in Gang of Four's observer pattern.
Used to decouple updating HUD (and playing sounds in the future) from `MainDude` states.
> Observer pattern

- cmake/DependenciesAndroid.cmake
- platforms/android/android-app/src/main/java/org/libsdl/app/HIDDevice.java
- platforms/android/android-app/src/main/java/org/libsdl/app/HIDDeviceBLESteamController.java
- platforms/android/android-app/src/main/java/org/libsdl/app/HIDDeviceManager.java
- platforms/android/android-app/src/main/java/org/libsdl/app/HIDDeviceUSB.java
- platforms/android/android-app/src/main/java/org/libsdl/app/SDL.java
- platforms/android/android-app/src/main/java/org/libsdl/app/SDLActivity.java
- platforms/android/android-app/src/main/java/org/libsdl/app/SDLAudioManager.java
- platforms/android/android-app/src/main/java/org/libsdl/app/SDLControllerManager.java
- readme/Building.md
- readme/Dependencies.md
- src/input/src/Input_Android.cpp
Upon adding new dependency that requires C++17 or higher, namely EnTT, Android NDK had to be upgraded as version r15c doesn't fully support it. That in turn made SDL2 2.0.9 fail to build, thus requiring upgrade to 2.0.14.
Docker image has already been updated - https://github.com/dbeef/spelunky-psp/pull/75
However, this follow-up MR exists for two reasons:
* new SDL2 2.0.14 needs additional runtime dependency to be copied into the .apk file - libhidapi.so.
* Java Activity copied from SDL2 sources and bundled in Spelunky-PSP needs to be synchronized with new SDL2 version
With the following changes the Android build is playable again.
> Android updated to SDL2 2.0.14

- src/game-loop/CMakeLists.txt
- src/game-loop/include/components/generic/ItemCarrierComponent.hpp
- src/game-loop/include/components/generic/ItemComponent.hpp
- src/game-loop/include/populator/Populator.hpp
- src/game-loop/interface/other/Inventory.hpp
- src/game-loop/interface/other/ItemType.hpp
- src/game-loop/src/components/generic/ItemCarrierComponent.cpp
- src/game-loop/src/game-loop/GameLoopLevelSummaryState.cpp
- src/game-loop/src/game-loop/GameLoopPlayingState.cpp
- src/game-loop/src/game-loop/GameLoopScoresState.cpp
- src/game-loop/src/other/Inventory.cpp
- src/game-loop/src/populator/Populator.cpp
- src/game-loop/src/prefabs/items/Arrow.cpp
- src/game-loop/src/prefabs/items/Bomb.cpp
- src/game-loop/src/prefabs/items/BombSpawner.cpp
- src/game-loop/src/prefabs/items/Cape.cpp
- src/game-loop/src/prefabs/items/Chest.cpp
- src/game-loop/src/prefabs/items/Crate.cpp
- src/game-loop/src/prefabs/items/Jar.cpp
- src/game-loop/src/prefabs/items/Jetpack.cpp
- src/game-loop/src/prefabs/items/Pistol.cpp
- src/game-loop/src/prefabs/items/Rock.cpp
- src/game-loop/src/prefabs/items/Rope.cpp
- src/game-loop/src/prefabs/items/RopeSpawner.cpp
- src/game-loop/src/prefabs/items/Shotgun.cpp
- src/game-loop/src/prefabs/items/Skull.cpp
- src/game-loop/src/prefabs/items/Whip.cpp
- src/game-loop/src/system/InputSystem.cpp
Main dude instance is created and disposed in each level - thus for saving permanent state, `Inventory` singleton is utilized (so far only for hearts/bombs/ropes/dollars).
I extended `Inventory` singleton to also save carried item types upon each `GameLoopPlayingState` exit and re-populate instances of them on each entry.
Inventory is cleaned upon entering `GameLoopScoresState`.
> Permanent item inventory

- src/game-loop/CMakeLists.txt
- src/game-loop/include/components/generic/ClimbingComponent.hpp
- src/game-loop/include/components/specialized/MainDudeComponent.hpp
- src/game-loop/include/main-dude/states/MainDudeClimbingState.hpp
- src/game-loop/src/main-dude/MainDudeComponent.cpp
- src/game-loop/src/main-dude/states/MainDudeClimbingLadderState.cpp
- src/game-loop/src/main-dude/states/MainDudeClimbingState.cpp
- src/game-loop/src/main-dude/states/MainDudeFallingState.cpp
- src/game-loop/src/main-dude/states/MainDudeJumpingState.cpp
- src/game-loop/src/main-dude/states/MainDudeRunningLookingUpState.cpp
- src/game-loop/src/main-dude/states/MainDudeRunningState.cpp
- src/game-loop/src/main-dude/states/MainDudeStandingState.cpp
- src/game-loop/src/prefabs/items/Rope.cpp
- src/game-loop/src/prefabs/items/RopeSpawner.cpp
- src/game-loop/src/prefabs/main-dude/MainDude.cpp
- src/game-loop/src/system/InputSystem.cpp
- src/level/interface/MapTile.hpp
- src/level/src/MapTile.cpp
- src/rendering-types/interface/Point2D.hpp
Climbing was removed in v0.4 due to rework to ECS - it didn't fit to the new system-based implementation and I couldn't place it into the release schedule as it was full already.
Changes:
* Climbing is handled in a generic way through `InputSystem` - entity must have a `ClimbingComponent` to climb
* `MapTile` now has a `climbable` property. It is set by default on ladder tiles and dynamically on tiles overlapping with rope.
* `MainDudeClimbingLadderState` is renamed to `MainDudeClimbingState` as it now handles both rope and ladder
> Re-implementing climbing with both ladders/ropes

- src/game-loop/CMakeLists.txt
- src/game-loop/include/components/damage/GiveNpcTouchDamageComponent.hpp
- src/game-loop/include/components/damage/TakeFallDamageComponent.hpp
- src/game-loop/include/components/damage/TakeNpcTouchDamageComponent.hpp
- src/game-loop/include/components/generic/BlinkingComponent.hpp
- src/game-loop/include/components/generic/QuadComponent.hpp
- src/game-loop/include/components/specialized/MainDudeComponent.hpp
- src/game-loop/include/main-dude/MainDudeObservers.hpp
- src/game-loop/include/system/DamageSystem.hpp
- src/game-loop/include/system/RenderingSystem.hpp
- src/game-loop/src/game-loop/GameLoopPlayingState.cpp
- src/game-loop/src/main-dude/MainDudeComponent.cpp
- src/game-loop/src/main-dude/MainDudeObservers.cpp
- src/game-loop/src/main-dude/states/MainDudeFallingState.cpp
- src/game-loop/src/prefabs/main-dude/MainDude.cpp
- src/game-loop/src/prefabs/npc/Bat.cpp
- src/game-loop/src/prefabs/npc/Caveman.cpp
- src/game-loop/src/prefabs/npc/Skeleton.cpp
- src/game-loop/src/prefabs/npc/Snake.cpp
- src/game-loop/src/prefabs/npc/Spider.cpp
- src/game-loop/src/system/DamageSystem.cpp
- src/game-loop/src/system/RenderingSystem.cpp
Changes:
* Added `GiveNpcTouchDamageComponent` and applied it to all NPC's (snake, bat, spider, skeleton, caveman)
* Added `TakeNpcTouchDamageComponent` and applied it to main dude
* Checking collisions between the new NPC damage components in `DamageSystem`
* Added `BlinkingComponent` and applying it on main dude taken damage.
Does not include damage taken from projectiles (i.e arrows, falling rocks).
> Main dude killable by NPC's

- src/game-loop/CMakeLists.txt
- src/game-loop/include/components/damage/GiveExplosionDamageComponent.hpp
- src/game-loop/include/components/damage/TakeExplosionDamageComponent.hpp
- src/game-loop/include/components/generic/PhysicsComponent.hpp
- src/game-loop/include/components/generic/ZoneComponent.hpp
- src/game-loop/include/components/specialized/MainDudeComponent.hpp
- src/game-loop/include/main-dude/MainDudeObservers.hpp
- src/game-loop/include/system/DamageSystem.hpp
- src/game-loop/src/components/generic/PhysicsComponent.cpp
- src/game-loop/src/components/specialized/LevelSummaryOverlayComponent.cpp
- src/game-loop/src/game-loop/GameLoopPlayingState.cpp
- src/game-loop/src/main-dude/MainDudeComponent.cpp
- src/game-loop/src/main-dude/MainDudeObservers.cpp
- src/game-loop/src/prefabs/effects/Explosion.cpp
- src/game-loop/src/prefabs/main-dude/MainDude.cpp
- src/game-loop/src/prefabs/npc/Bat.cpp
- src/game-loop/src/prefabs/npc/Caveman.cpp
- src/game-loop/src/prefabs/npc/Skeleton.cpp
- src/game-loop/src/prefabs/npc/Snake.cpp
- src/game-loop/src/prefabs/npc/Spider.cpp
- src/game-loop/src/system/DamageSystem.cpp
Changes:
* Explosions now give damage to each entity that has `TakeExplosionDamageComponent`
* Introduced `ZoneComponent` existing of width/height
* Each entity within the zone that has at least physics/position components will be moved away out of explosion (direction-wise)
* Main dude gets `ParticleEmitterComponent` attached upon death by explosion (so to emit flame particles)
> (extended) explosion

- src/game-loop/include/components/damage/GiveProjectileDamageComponent.hpp
- src/game-loop/include/components/damage/HitpointComponent.hpp
- src/game-loop/include/components/specialized/MainDudeComponent.hpp
- src/game-loop/include/main-dude/MainDudeObservers.hpp
- src/game-loop/include/prefabs/items/Arrow.hpp
- src/game-loop/include/prefabs/other/Bullet.hpp
- src/game-loop/src/components/generic/ItemCarrierComponent.cpp
- src/game-loop/src/components/specialized/DeathOverlayComponent.cpp
- src/game-loop/src/main-dude/MainDudeComponent.cpp
- src/game-loop/src/main-dude/MainDudeObservers.cpp
- src/game-loop/src/prefabs/items/Arrow.cpp
- src/game-loop/src/prefabs/items/Jar.cpp
- src/game-loop/src/prefabs/items/Pistol.cpp
- src/game-loop/src/prefabs/items/Shotgun.cpp
- src/game-loop/src/prefabs/items/Skull.cpp
- src/game-loop/src/prefabs/main-dude/MainDude.cpp
- src/game-loop/src/prefabs/npc/Bat.cpp
- src/game-loop/src/prefabs/npc/Caveman.cpp
- src/game-loop/src/prefabs/npc/Skeleton.cpp
- src/game-loop/src/prefabs/npc/Snake.cpp
- src/game-loop/src/prefabs/npc/Spider.cpp
- src/game-loop/src/prefabs/other/Bullet.cpp
- src/game-loop/src/prefabs/traps/ArrowTrap.cpp
- src/game-loop/src/system/DamageSystem.cpp
Main dude taking projectile damage causes the following design problem - 
*How to differentiate between projectiles that the main dude has just thrown,
and the ones from outside, i.e from arrow trap?*
Possible solutions:
a) add position offset immediately after throwing a projectile so there would be no collision
b) when checking collisions, ignore projectiles moving away?
c) give a high velocity treshold only after which damage is applied?
d) carry some indicator (i.e component) that would store source of projectile (i.e arrow trop, main dude, nothing)
e) **save entity id of projectile source (i.e main dude if thrown it) and ignore it when checking collision**
f) short cooldown just after throwing something?
So far I decided to stick to e), but it is not definitive.
Changes: 
* Added …
> Main dude now takes projectile damage

- src/game-loop/src/prefabs/traps/ArrowTrap.cpp
- src/game-loop/src/system/DamageSystem.cpp
Untill now, only arrow-trap tile was removed upon explosion - meaning that arrow was still spawned there when trap triggered (although the trap was invisible at this point).
> Disposing arrow-trap entity upon explosion

- src/game-loop/CMakeLists.txt
- src/game-loop/include/components/damage/GiveSpikesDamageComponent.hpp
- src/game-loop/include/components/damage/TakeSpikesDamageComponent.hpp
- src/game-loop/include/components/specialized/MainDudeComponent.hpp
- src/game-loop/include/main-dude/MainDudeObservers.hpp
- src/game-loop/include/system/DamageSystem.hpp
- src/game-loop/src/main-dude/MainDudeComponent.cpp
- src/game-loop/src/main-dude/MainDudeObservers.cpp
- src/game-loop/src/prefabs/main-dude/MainDude.cpp
- src/game-loop/src/prefabs/npc/Caveman.cpp
- src/game-loop/src/prefabs/npc/Snake.cpp
- src/game-loop/src/prefabs/npc/Spider.cpp
- src/game-loop/src/prefabs/traps/Spikes.cpp
- src/game-loop/src/system/DamageSystem.cpp
Changes:
* Bomb explosions destroy spikes
* New components - `TakeSpikesDamageComponent`, `GiveSpikesDamageComponent`, updated in `DamageSystem`
* Main dude, caveman, spider, snake can be now killed by spikes
* Spike kill after reaching treshold vertical speed + overlaping with other body
> Spikes taking explosion damage

- src/game-loop/interface/game-loop/GameLoop.hpp
- src/game-loop/src/game-loop/GameLoop.cpp
- src/game-loop/src/game-loop/GameLoopPlayingState.cpp
- src/level/src/TileBatch.cpp
Turns out `std::srand` wasn't called before `std::rand`.
Using time elapsed since the beginning of the game as seed.
Also, removed C++11 random number generation as it was seemingly unaffected by the fix (underlying newlib libc problem?).
> Fixed random number generation on PSP

- src/game-loop/src/components/specialized/LevelSummaryTracker.cpp
- src/game-loop/src/game-loop/GameLoopPlayingState.cpp
- src/game-loop/src/main-dude/MainDudeObservers.cpp
- src/game-loop/src/prefabs/items/Bomb.cpp
- src/game-loop/src/prefabs/npc/Bat.cpp
- src/game-loop/src/prefabs/npc/CavemanScript.cpp
- src/game-loop/src/prefabs/npc/DamselScript.cpp
- src/game-loop/src/prefabs/npc/ShopkeeperScript.cpp
- src/game-loop/src/prefabs/npc/Snake.cpp
- src/game-loop/src/prefabs/npc/Spider.cpp
- src/input/src/Input_PSP.cpp
* Limited number of particles by 50% (due to PSP performance)
* Changed PSP key bindings
* Removing NPC events from previous level in `LevelSummaryTracker`
* Removing `ShoppingSystem` observers upon state exit
> Pre-release test findings

- src/input/src/Input_Android.cpp
- src/input/src/Input_Darwin.cpp
As in title. Caused picked-up items to be dropped instantly.
> Fixed the pick-up bug on platforms with input based on SDL2
